# Generated by Django 3.2.7 on 2021-11-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_group_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
